package gov.nist.pededitor;

import java.awt.Frame;
import java.awt.geom.Point2D;

import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import org.codehaus.jackson.annotate.JsonIgnore;

/** GUI to display information about a tangency point in the
    diagram. */
public class VertexInfoDialog extends JDialog {
    private static final long serialVersionUID = 1686051698640332170L;

    // TODO Use diagram components to determine slope.

    public JTextField angle = new JTextField("180.00", 9);
    public JTextField slope = new JTextField("9999.99", 12);

    public boolean selfModifying = false;
    JLabel slopeLabel;
    public JLabel lineWidth = new JLabel("0.00000");

    public VertexInfoDialog(Frame owner) {
        super(owner, "Tangent", false);

        slope.getDocument().addDocumentListener
            (new DocumentListener() {
                    @Override public void changedUpdate(DocumentEvent e) {
                        if (selfModifying) {
                            // This event was presumably generated by
                            // another event.
                            return;
                        }
                        try {
                            selfModifying = true;
                            double s = ContinuedFraction.parseDouble(slope.getText());
                            setAngle(slopeToTheta(s));
                        } catch (NumberFormatException ex) {
                            return;
                        } finally {
                            selfModifying = false;
                        }
                    }

                    @Override public void insertUpdate(DocumentEvent e) {
                        changedUpdate(e);
                    }

                    @Override public void removeUpdate(DocumentEvent e) {
                        changedUpdate(e);
                    }
                });

        angle.getDocument().addDocumentListener
            (new DocumentListener() {
                    @Override public void changedUpdate(DocumentEvent e) {
                        if (selfModifying) {
                            // This event was presumably generated by
                            // another event.
                            return;
                        }
                        try {
                            selfModifying = true;
                            double deg = ContinuedFraction.parseDouble(angle.getText());
                            setSlope(thetaToSlope(degreesToTheta(deg)));
                        } catch (NumberFormatException ex) {
                            return;
                        } finally {
                            selfModifying = false;
                        }
                    }

                    @Override public void insertUpdate(DocumentEvent e) {
                        changedUpdate(e);
                    }

                    @Override public void removeUpdate(DocumentEvent e) {
                        changedUpdate(e);
                    }
                });

        GridBagUtil gb = new GridBagUtil(getContentPane());

        gb.addEast(new JLabel("Angle:"));
        gb.addWest(angle);
        gb.endRowWith(new JLabel("\u00B0") /* degree symbol */);

        gb.addEast(new JLabel("Slope:"));
        gb.endRowWith(slope);

        gb.addEast(new JLabel("Line width:"));
        gb.endRowWith(lineWidth);
        pack();
        setDerivative(null);
        setLineWidth(0.0);
    }

    public void setDerivative(Point2D point) {
        double x = (point == null) ? 0 : point.getX();
        double y = (point == null) ? 0 : point.getY();
        if (x == 0 && y == 0) {
            angle.setText("");
            slope.setText("");
            return;
        }

        if (x == 0) {
            slope.setText("");
        } else {
            setSlope(y/x);
        }

        setAngle(Math.atan2(y, x));
    }

    public double thetaToDegrees(double theta) {
        double deg = -theta * 180 / Math.PI;
        if (deg < -90) {
            deg += 180;
        } else if (deg > 90) {
            deg -= 180;
        }
        return deg;
    }

    public double degreesToTheta(double deg) {
        return -deg * Math.PI / 180;
    }

    public double thetaToSlope(double theta) {
        return Math.tan(theta);
    }

    public double slopeToTheta(double s) {
        return -Math.atan2(s, 1);
    }

    public void setAngle(double theta) {
        setAngleDegrees(thetaToDegrees(theta));
    }

    public void setAngleDegrees(double deg) {
        angle.setText(String.format("%.2f", deg));
        repaint();
    }

    @JsonIgnore
    public double getAngleDegrees() {
        try {
            return ContinuedFraction.parseDouble(angle.getText());
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    public double getAngle() {
        return Compass.degreesToTheta(getAngleDegrees());
    }

    public void setSlope(double m) {
        slope.setText(String.format("%.4f", -m));
        repaint();
    }

    public void setSlopeLabel(String label) {
        slopeLabel.setText(label + ":");
        repaint();
    }

    // TODO Kind of lame -- use full precision slope instead of using
    // the displayed approximation.
    public double getSlope() {
        try {
            return ContinuedFraction.parseDouble(slope.getText());
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    public void setLineWidth(double w) {
        lineWidth.setText(String.format("%.5f", w));
        repaint();
    }
    
}
